# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4bd78508ebd69496bc580e4f32fae54e0d16a05c226931a918000426748ed855d3a344b59cf39f3b9a25bb30bcc6c9971c9314b3d30ee4ae5bb67d9a34654af7

test:
  secret_key_base: 3fd8cc7f5532fd300e53a2340b1dc9c0234552c532671d80ff58ebdbcd37a011092366e6c3056dc7f551239f1b79d4a805193b3a7c6619778050cd734463d5a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
