# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5ccc4daacb40f3eded4d6f54827f0fb0a11a8aefbc963c895c422d457ccf8db3e30e197d4fe3613c0536858983a93e7973d4c7b58d3133b7a34ff795e5b8254

test:
  secret_key_base: a37555d30b14eaf26bc3a29a27f3480bcb5de710377c818b73e2ad0cf9967ecb804209dc5b67f3edcefac178cb17800a4132fa48f4641c8450eab21ff90f3578

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
